// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reward.Infrastructure.Persistence;

#nullable disable

namespace Reward.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RewardDbContext))]
    partial class RewardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reward.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.ClassTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("class_tag", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_instance_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ItemInstanceId");

                    b.HasIndex("SlotId");

                    b.HasIndex("HeroId", "SlotId")
                        .IsUnique();

                    b.ToTable("equipment", null, t =>
                        {
                            t.HasCheckConstraint("ck_equipment_quantity_one", "quantity = 1");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.EquipmentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("slot", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.EquipmentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("InventorySnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_snapshot_id");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_instance_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.HasKey("Id");

                    b.HasIndex("InventorySnapshotId");

                    b.HasIndex("ItemInstanceId");

                    b.HasIndex("SlotId");

                    b.ToTable("equipment_snapshot", null, t =>
                        {
                            t.HasCheckConstraint("ck_equipment_snapshot_quantity_one", "quantity = 1");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("HeroId")
                        .HasColumnType("uuid")
                        .HasColumnName("hero_id");

                    b.Property<int>("ItemCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("item_capacity");

                    b.Property<int>("PotionCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("potion_capacity");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("inventory", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_capacities", "item_capacity > 0 AND potion_capacity > 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.InventorySnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId", "RunId")
                        .IsUnique();

                    b.ToTable("inventory_snapshot", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("LevelRequired")
                        .HasColumnType("integer")
                        .HasColumnName("level_required");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("RarityId")
                        .HasColumnType("uuid")
                        .HasColumnName("rarity_id");

                    b.Property<bool>("Stackable")
                        .HasColumnType("boolean")
                        .HasColumnName("stackable");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RarityId");

                    b.ToTable("item", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemClassTag", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("ClassTagId")
                        .HasColumnType("uuid")
                        .HasColumnName("class_tag_id");

                    b.HasKey("ItemId", "ClassTagId");

                    b.HasIndex("ClassTagId");

                    b.ToTable("item_class_tag", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InventoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("item_instance", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_instance_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemModifier", b =>
                {
                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("ModifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("modifier_id");

                    b.HasKey("ItemId", "ModifierId");

                    b.HasIndex("ModifierId");

                    b.ToTable("item_modifier", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventorySnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_snapshot_id");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_instance_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasKey("Id");

                    b.HasIndex("InventorySnapshotId");

                    b.HasIndex("ItemInstanceId");

                    b.ToTable("item_snapshot", null, t =>
                        {
                            t.HasCheckConstraint("ck_item_snapshot_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.LootRarityRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("LootTableId")
                        .HasColumnType("uuid")
                        .HasColumnName("loot_table_id");

                    b.Property<Guid>("RarityId")
                        .HasColumnType("uuid")
                        .HasColumnName("rarity_id");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("LootTableId");

                    b.HasIndex("RarityId");

                    b.ToTable("loot_rarity_rule", null, t =>
                        {
                            t.HasCheckConstraint("ck_loot_rarity_rule_weight", "weight > 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.LootTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("loot_table", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.LootTableEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid>("LootRarityRuleId")
                        .HasColumnType("uuid")
                        .HasColumnName("loot_rarity_rule_id");

                    b.Property<int>("MaxQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("max_quantity");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("min_quantity");

                    b.Property<int>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("LootRarityRuleId");

                    b.ToTable("loot_table_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_loot_table_entry_quantities", "weight > 0 AND min_quantity > 0 AND max_quantity >= min_quantity");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.MarketplaceListing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_instance_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ItemInstanceId")
                        .IsUnique()
                        .HasDatabaseName("uq_active_listing_item")
                        .HasFilter("status IN ('ACTIVE', 'RESERVED')");

                    b.ToTable("marketplace_listing", null, t =>
                        {
                            t.HasCheckConstraint("ck_listing_quantity_price", "quantity > 0 AND price >= 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.MarketplaceReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ListingId")
                        .IsUnique()
                        .HasDatabaseName("uq_active_reservation_listing")
                        .HasFilter("status = 'ACTIVE'");

                    b.ToTable("marketplace_reservation", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.MarketplaceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ListingId");

                    b.HasIndex("ReservationId");

                    b.ToTable("marketplace_transaction", null, t =>
                        {
                            t.HasCheckConstraint("ck_transaction_idempotency_key_nonblank", "length(btrim(idempotency_key)) > 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.Modifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Stat")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stat");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("modifier", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.OwnershipTransfer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromInventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_inventory_id");

                    b.Property<Guid>("FromOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_owner_id");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_instance_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("ToInventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_inventory_id");

                    b.Property<Guid>("ToOwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_owner_id");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.HasIndex("FromInventoryId");

                    b.HasIndex("ItemInstanceId");

                    b.HasIndex("ToInventoryId");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.ToTable("ownership_transfer", null, t =>
                        {
                            t.HasCheckConstraint("ck_ownership_transfer_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.Placeholder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("placeholder", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.Rarity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Rank")
                        .IsUnique();

                    b.ToTable("rarity", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.Reward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RewardKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reward_key");

                    b.Property<Guid>("RewardSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_source_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("XpAmount")
                        .HasColumnType("integer")
                        .HasColumnName("xp_amount");

                    b.HasKey("Id");

                    b.HasIndex("RewardKey")
                        .IsUnique();

                    b.HasIndex("RewardSourceId");

                    b.ToTable("reward", null, t =>
                        {
                            t.HasCheckConstraint("ck_reward_key_nonblank", "length(btrim(reward_key)) > 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.RewardItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("ItemInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_instance_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uuid")
                        .HasColumnName("reward_id");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemInstanceId");

                    b.HasIndex("RewardId");

                    b.ToTable("reward_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_reward_item_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.RewardSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("reward_source", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.RunEquipmentState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RunInventorySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_inventory_session_id");

                    b.Property<Guid>("RunItemStateId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_item_state_id");

                    b.Property<Guid>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RunItemStateId");

                    b.HasIndex("SlotId");

                    b.HasIndex("RunInventorySessionId", "SlotId")
                        .IsUnique();

                    b.ToTable("run_equipment_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_run_equipment_quantity_one", "quantity = 1");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.RunInventorySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<Guid>("InventorySnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_snapshot_id");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phase");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InventorySnapshotId")
                        .IsUnique();

                    b.ToTable("run_inventory_session", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.RunItemState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Guid?>("ItemInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_instance_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<Guid>("RunInventorySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_inventory_session_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ItemInstanceId");

                    b.HasIndex("RunInventorySessionId");

                    b.ToTable("run_item_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_run_item_state_quantity", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CashAdjustment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cash_adjustment");

                    b.Property<Guid>("CounterpartyId")
                        .HasColumnType("uuid")
                        .HasColumnName("counterparty_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiator_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("trade", (string)null);
                });

            modelBuilder.Entity("Reward.Domain.Entities.TradeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ItemInstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_instance_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("side");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ItemInstanceId");

                    b.HasIndex("TradeId");

                    b.ToTable("trade_item", null, t =>
                        {
                            t.HasCheckConstraint("ck_trade_item_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("wallet", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallet_balance", "balance >= 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.WalletHold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HoldKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hold_key");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("HoldKey")
                        .IsUnique();

                    b.HasIndex("TradeId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("WalletId");

                    b.ToTable("wallet_hold", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallet_hold_amount", "amount > 0");

                            t.HasCheckConstraint("ck_wallet_hold_single_origin", "(id_transaction IS NOT NULL) <> (id_trade IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.WalletLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Delta")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("delta");

                    b.Property<string>("OperationKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_key");

                    b.Property<Guid?>("WalletHoldId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_hold_id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("OperationKey")
                        .IsUnique();

                    b.HasIndex("WalletHoldId");

                    b.HasIndex("WalletId");

                    b.ToTable("wallet_ledger_entry", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallet_ledger_nonzero", "delta <> 0");
                        });
                });

            modelBuilder.Entity("Reward.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("Reward.Domain.Entities.ItemInstance", "ItemInstance")
                        .WithMany("Equipment")
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.EquipmentSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemInstance");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Reward.Domain.Entities.EquipmentSnapshot", b =>
                {
                    b.HasOne("Reward.Domain.Entities.InventorySnapshot", "InventorySnapshot")
                        .WithMany()
                        .HasForeignKey("InventorySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.EquipmentSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventorySnapshot");

                    b.Navigation("ItemInstance");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Reward.Domain.Entities.InventorySnapshot", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Inventory", "Inventory")
                        .WithMany("Snapshots")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Reward.Domain.Entities.Item", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.Rarity", "Rarity")
                        .WithMany("Items")
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemClassTag", b =>
                {
                    b.HasOne("Reward.Domain.Entities.ClassTag", "ClassTag")
                        .WithMany("Items")
                        .HasForeignKey("ClassTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.Item", "Item")
                        .WithMany("ClassTags")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassTag");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemInstance", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Inventory", "Inventory")
                        .WithMany("ItemInstances")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.Item", "Item")
                        .WithMany("Instances")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Inventory");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemModifier", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Item", "Item")
                        .WithMany("Modifiers")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.Modifier", "Modifier")
                        .WithMany("Items")
                        .HasForeignKey("ModifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Modifier");
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemSnapshot", b =>
                {
                    b.HasOne("Reward.Domain.Entities.InventorySnapshot", "InventorySnapshot")
                        .WithMany("ItemSnapshots")
                        .HasForeignKey("InventorySnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventorySnapshot");

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("Reward.Domain.Entities.LootRarityRule", b =>
                {
                    b.HasOne("Reward.Domain.Entities.LootTable", "LootTable")
                        .WithMany()
                        .HasForeignKey("LootTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.Rarity", "Rarity")
                        .WithMany()
                        .HasForeignKey("RarityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LootTable");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("Reward.Domain.Entities.LootTableEntry", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.LootRarityRule", "LootRarityRule")
                        .WithMany()
                        .HasForeignKey("LootRarityRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("LootRarityRule");
                });

            modelBuilder.Entity("Reward.Domain.Entities.MarketplaceListing", b =>
                {
                    b.HasOne("Reward.Domain.Entities.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ItemInstance");
                });

            modelBuilder.Entity("Reward.Domain.Entities.MarketplaceReservation", b =>
                {
                    b.HasOne("Reward.Domain.Entities.MarketplaceListing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("Reward.Domain.Entities.MarketplaceTransaction", b =>
                {
                    b.HasOne("Reward.Domain.Entities.MarketplaceListing", "Listing")
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.MarketplaceReservation", "Reservation")
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Listing");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Reward.Domain.Entities.OwnershipTransfer", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Inventory", "FromInventory")
                        .WithMany()
                        .HasForeignKey("FromInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.Inventory", "ToInventory")
                        .WithMany()
                        .HasForeignKey("ToInventoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.MarketplaceTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromInventory");

                    b.Navigation("ItemInstance");

                    b.Navigation("ToInventory");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("Reward.Domain.Entities.Reward", b =>
                {
                    b.HasOne("Reward.Domain.Entities.RewardSource", "RewardSource")
                        .WithMany()
                        .HasForeignKey("RewardSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RewardSource");
                });

            modelBuilder.Entity("Reward.Domain.Entities.RewardItem", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reward.Domain.Entities.Reward", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemInstance");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("Reward.Domain.Entities.RunEquipmentState", b =>
                {
                    b.HasOne("Reward.Domain.Entities.RunInventorySession", "RunInventorySession")
                        .WithMany()
                        .HasForeignKey("RunInventorySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.RunItemState", "RunItemState")
                        .WithMany()
                        .HasForeignKey("RunItemStateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.EquipmentSlot", "Slot")
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RunInventorySession");

                    b.Navigation("RunItemState");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Reward.Domain.Entities.RunInventorySession", b =>
                {
                    b.HasOne("Reward.Domain.Entities.InventorySnapshot", "InventorySnapshot")
                        .WithMany()
                        .HasForeignKey("InventorySnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InventorySnapshot");
                });

            modelBuilder.Entity("Reward.Domain.Entities.RunItemState", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reward.Domain.Entities.RunInventorySession", "RunInventorySession")
                        .WithMany()
                        .HasForeignKey("RunInventorySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("ItemInstance");

                    b.Navigation("RunInventorySession");
                });

            modelBuilder.Entity("Reward.Domain.Entities.TradeItem", b =>
                {
                    b.HasOne("Reward.Domain.Entities.ItemInstance", "ItemInstance")
                        .WithMany()
                        .HasForeignKey("ItemInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Reward.Domain.Entities.Trade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemInstance");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("Reward.Domain.Entities.WalletHold", b =>
                {
                    b.HasOne("Reward.Domain.Entities.Trade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reward.Domain.Entities.MarketplaceTransaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reward.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trade");

                    b.Navigation("Transaction");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Reward.Domain.Entities.WalletLedgerEntry", b =>
                {
                    b.HasOne("Reward.Domain.Entities.WalletHold", "WalletHold")
                        .WithMany()
                        .HasForeignKey("WalletHoldId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Reward.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");

                    b.Navigation("WalletHold");
                });

            modelBuilder.Entity("Reward.Domain.Entities.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Reward.Domain.Entities.ClassTag", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Reward.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("ItemInstances");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Reward.Domain.Entities.InventorySnapshot", b =>
                {
                    b.Navigation("ItemSnapshots");
                });

            modelBuilder.Entity("Reward.Domain.Entities.Item", b =>
                {
                    b.Navigation("ClassTags");

                    b.Navigation("Instances");

                    b.Navigation("Modifiers");
                });

            modelBuilder.Entity("Reward.Domain.Entities.ItemInstance", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Reward.Domain.Entities.Modifier", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Reward.Domain.Entities.Rarity", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
